apiVersion: v1
kind: Service
metadata:
  name: mimock-svc
spec:
  type: NodePort
  selector:
    app: mimock
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
