version: "3.3"
services:
  mimock-pg-database:
    container_name: mimock-pg-database
    image: postgres:13.5-alpine
    env_file:
      - local.env
    networks:
      - mimock-network
    ports:
      - "5427:5432"

networks:
  mimock-network:
