version: "3.3"
services:
  mimock-db:
    container_name: mimock-db
    image: postgres:13.5-alpine
    env_file:
      - local.env
    networks:
      - mimock-network
    ports:
      - "5427:5432"

  mimock:
    depends_on:
      - mimock-db
    build:
      context: .
    container_name: mimock
    networks:
      - mimock-network
    ports:
      - "8080:8080"
    env_file:
      - local.env
    image: mimock/mimock:latest
    volumes:
      - ./mimock.jks:/home/mimock/mimock.jks

networks:
  mimock-network:
