version: "3.3"
services:
  mimock-pg-database:
    container_name: mimock-pg-database
    image: postgres:13.5-alpine
    restart: on-failure
    env_file:
      - local.env
    networks:
      - mimock-network
    ports:
      - "5427:5432"

  mimock:
    depends_on:
      - mimock-pg-database
    build:
      context: .
    container_name: mimock
    networks:
      - mimock-network
    ports:
      - "9002:8080"
    env_file:
      - local.env
    image: mimock

networks:
  mimock-network:
