logging:
  level:
    root: ${MIMOCK_LOG_LEVEL}

server:
  ssl:
    enabled: '${MIOMCK_KEYSTORE_ENABLE}'
    key-store: '${MIMOCK_KEYSTORE_PATH}'
    key-store-password: '${MIOMCK_KEYSTORE_PASSWORD}'
    key-store-type: PKCS12
    enabled-protocols: TLSv1.3

spring:
  main:
    banner-mode: off

  web:
    resources:
      static-locations: classpath:/static/mimock-ui/

  servlet:
    multipart:
      max-file-size: 10MB
      resolve-lazily: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  devtools:
    restart:
      enabled: 'true'
      poll-interval: 1s
    livereload:
      enabled: 'true'

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${MIMOCK_DB_SCHEMA}
        types:
          print:
            banner: false

  datasource:
    url: ${MIMOCK_DB_URL} # E.g: jdbc:postgresql://localhost:5427/mimock_db
    username: ${MIMOCK_DB_USER}
    password: ${MIMOCK_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${MIMOCK_DB_SCHEMA}

  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
    default-schema: ${MIMOCK_DB_SCHEMA}
    liquibase-schema: ${MIMOCK_DB_SCHEMA}
    user: ${MIMOCK_DB_USER}
    password: ${MIMOCK_DB_PASSWORD}

app:
  security:
    jwt-expiry-in-seconds: ${MIMOCK_JWT_EXPIRY_IN_SECONDS}
    jwt-secret-key: ${MIMOCK_JWT_SECRET} # Only for testing. Do not use this in production.
    cors-config:
      allowed-origins: http://localhost:3000,http://localhost:3001

springdoc:
  swagger-ui:
    doc-expansion: none
    csrf:
      enabled: true
      header-name: X-XSRF-TOKEN

flush-bin-cron-expression: "0 0 3 1 * *"