# These configurations are purely for development purposes.
# It is not be used in the production environment.
logging:
  level:
    root: INFO

server:
  error:
    whitelabel:
      enabled: false
  ssl:
    enabled: false
    key-store: src/main/resources/keystore/keystore.p12
    key-store-password: ironclaw
    key-store-type: PKCS12
    enabled-protocols: TLSv1.3

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      resolve-lazily: true

  web:
    resources:
      static-locations: classpath:/static/mimock-ui/

  devtools:
    restart:
      enabled: true
      poll-interval: 1s
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: mimock_schema_dev
        types:
          print:
            banner: false

  datasource:
    url: jdbc:postgresql://localhost:5427/mimock_db
    username: mimock
    password: ironclaw
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: mimock_schema_dev
      auto-commit: false

  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
    default-schema: mimock_schema_dev
    liquibase-schema: mimock_schema_dev
    user: mimock
    password: ironclaw

app:
  security:
    jwt-expiry-in-seconds: 1800
    jwt-secret-key: B4982E53863B4DA7FDA4E1236C4BAF8A # Only for development. Do not use this in production.
    cors-config:
      allowed-origins: http://localhost:3000,http://localhost:3001

springdoc:
  swagger-ui:
    csrf:
      enabled: true
      header-name: X-XSRF-TOKEN