logging:
  level:
    root: ERROR

spring:
  datasource:
    url: '${MIMOCK_DB_URL}'
    username: mimock
    password: ironclaw
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: mimock_schema_test

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
    default-schema: mimock_schema_test
    liquibase-schema: mimock_schema_test

app:
  url_prefix: /api/mimock/v1
