logging:
  level:
    root: ${MIMOCK_LOG_LEVEL}

server:
  ssl:
    enabled: '${MIOMCK_KEYSTORE_ENABLE}'
    key-store: '${MIMOCK_KEYSTORE_PATH}'
    key-store-password: '${MIOMCK_KEYSTORE_PASSWORD}'
    key-store-type: PKCS12
    enabled-protocols: TLSv1.3

spring:
  main:
    banner-mode: off

  web:
    resources:
      static-locations: classpath:/static/mimock-ui/

  servlet:
    multipart:
      max-file-size: 10MB
      resolve-lazily: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  devtools:
    restart:
      enabled: 'true'
      poll-interval: 1s
    livereload:
      enabled: 'true'

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${MIMOCK_DB_SCHEMA}
        types:
          print:
            banner: false

  datasource:
    url: ${MIMOCK_DB_URL} # E.g: jdbc:postgresql://localhost:5432/mimock_db
    username: ${MIMOCK_DB_USER}
    password: ${MIMOCK_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${MIMOCK_DB_SCHEMA}

  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
    default-schema: ${MIMOCK_DB_SCHEMA}
    liquibase-schema: ${MIMOCK_DB_SCHEMA}
    user: ${MIMOCK_DB_USER}
    password: ${MIMOCK_DB_PASSWORD}

app:
  security:
    # NOTES
    # Session timeout value accepts time tokens such as 1s, 2h, 35m etc.,
    # Allowed values
    # s - seconds | m - minutes | h - hours | d - days | w - weeks | M - months | y - years
    # It accepts only whole numeric values (E.g: 210m => Valid ; 3.5h => Invalid)
    # If the token is invalid, then the default timeout value will be used ( 1 Hour )
    jwt-expiry-duration: ${MIMOCK_JWT_EXPIRY_DURATION}
    # End
    jwt-secret-key: ${MIMOCK_JWT_SECRET}
    cors-config:
      allowed-origins: ${MIMOCK_CORS_ORIGINS}
      allowed-methods: ${MIMOCK_CORS_METHODS}
      allowed-headers: ${MIMOCK_CORS_ALLOWED_HEADERS}
      exposed-headers: ${MIMOCK_CORS_EXPOSED_HEADERS}


springdoc:
  swagger-ui:
    doc-expansion: none
    csrf:
      enabled: true
      header-name: X-XSRF-TOKEN

flush-bin-cron-expression: "0 0 3 1 * *"

management:
  endpoints:
    web:
      base-path: "/api/mimock/monitoring"
      exposure:
        include:
          - health
          - info
          - prometheus