server:
  ssl:
    enabled: false
    key-store: src/main/resources/keystore/keystore.p12
    key-store-password: ironclaw
    key-store-type: PKCS12
    enabled-protocols: TLSv1.3

spring:
  devtools:
    restart:
      enabled: true
      poll-interval: 1s
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: mimock_schema_dev

  datasource:
    url: jdbc:postgresql://localhost:5427/mimock_db
    username: mimock
    password: ironclaw
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: mimock_schema_dev
      auto-commit: false

  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
    default-schema: mimock_schema_dev
    liquibase-schema: mimock_schema_dev

app:
  url_prefix: /api/mimock/v1
