server:
  ssl:
    enabled: '${MIOMCK_KEYSTORE_ENABLE}'
    key-store: '${MIMOCK_KEYSTORE_PATH}'
    key-store-password: '${MIOMCK_KEYSTORE_PASSWORD}'
    key-store-type: PKCS12
    enabled-protocols: TLSv1.3

spring:
  devtools:
    restart:
      enabled: 'true'
      poll-interval: 1s
    livereload:
      enabled: 'true'

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${MIMOCK_DB_SCHEMA}
        types:
          print:
            banner: false

  datasource:
    url: ${MIMOCK_DB_URL} # E.g: jdbc:postgresql://localhost:5427/mimock_db
    username: ${MIMOCK_DB_USER}
    password: ${MIMOCK_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${MIMOCK_DB_SCHEMA}

  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
    default-schema: ${MIMOCK_DB_SCHEMA}
    liquibase-schema: ${MIMOCK_DB_SCHEMA}
    user: ${MIMOCK_DB_USER}
    password: ${MIMOCK_DB_PASSWORD}

app:
  origin: http://localhost:3000
  security:
    jwt-expiry-in-seconds: 1800
    jwt-secret-key: C4BE6B45CBBD4CBADFE5E22F4BCDBAF8 # Only for testing. Do not use this in production.
    cors-config:
      allowed-origins: http://localhost:3000,http://localhost:3001