name: 'mimock artifacts cleanup'
on:
  schedule:
    - cron: '0 * * * *' # every night at 4 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
          expire-in: 0 # Setting this to 0 will delete all artifacts
