name: Mimock Bundle App Pipeline

on:
  push:
    branches: [main]

jobs:
  hold-bundling:
    name: Wait for manual trigger
    runs-on: ubuntu-latest
    environment:
      name: mimockRelease

  bundle-app:
    name: Bundle spring-boot app with UI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Mimock app
        working-directory: mimock-backend
        run: ./mvnw clean package -P productionBundle

      - name: Publish JAR
        uses: actions/upload-artifact@v2
        with:
          name: mimock-jar
          path: |
            ./mimock-backend/target/mimock-*.jar

      - name: Build mimock docker image
        run: |
          docker build -t mimock:${{ github.sha }} . -f ./Dockerfile.min
          docker save -o mimock.zip mimock:${{ github.sha }}

      - name: Publish docker image archive
        uses: actions/upload-artifact@v2
        with:
          name: mimock-docker-image
          path: |
            mimock.zip
