name: Mimock Bundle App Pipeline

on: [workflow_dispatch]

jobs:
  bundle-app:
    name: Bundle spring-boot app with UI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Mimock app
        run: |
          make bundle-app

      - name: Publish JAR
        uses: actions/upload-artifact@v2
        with:
          name: mimock-${{ secrets.MIMOCK_CURRENT_VERSION }}-jar.zip
          path: |
            ./mimock-backend/target/mimock-${{ secrets.MIMOCK_CURRENT_VERSION }}.jar

      - name: Build mimock docker image
        run: |
          docker build -t mimock-backend:${{ github.sha }} . -f ./Dockerfile.min && echo "Docker image build validated"
          docker system prune -f && docker image prune --all -f
