name: Mimock Bundle App Pipeline

on:
  push:
    branches: [main]

jobs:
  hold-bundling:
    name: Wait for manual trigger
    runs-on: ubuntu-latest
    environment:
      name: mimockRelease

    steps:
      - name: Wait for reviewer to initiate the build
        run: |
          echo "Awaiting Review!"

  bundle-app:
    name: Bundle spring-boot app with UI
    needs:
      - hold-bundling
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Mimock app
        working-directory: mimock-backend
        run: |
          ./mvnw initialize -P startDatabase
          ./mvnw -ntp clean package -P productionBundle
          jar -tf ./target/mimock-0.0.1.jar | grep 'mimock-ui'

      - name: Publish JAR
        uses: actions/upload-artifact@v2
        with:
          name: mimock-jar
          path: |
            ./mimock-backend/target/mimock-*.jar

      - name: Build mimock docker image
        run: |
          docker build -t mimock-backend:${{ github.sha }} . -f ./Dockerfile.min && echo "Docker image build validated"
          docker system prune -f && docker image prune --all -f
